// This file is automatically generated by @gschz/astro-plugin-i18n
// Do not modify it manually, as it will be overwritten.

/**
 * Types for the i18n system generated from the default language translations.
 */

/**
 * Type representing the supported language codes.
 */
export type Lang = 'es' | 'en' | 'pt-BR';
export type GeneratedLanguage = Lang;

/**
 * Type representing all available translation keys.
 */
export type I18nKey =
  | 'common:controls.body'
  | 'common:controls.clientStatus'
  | 'common:controls.title'
  | 'common:demo.meta.description'
  | 'common:demo.meta.pageTitle'
  | 'common:demo.react.currentLanguage'
  | 'common:demo.react.description'
  | 'common:demo.react.eventCount'
  | 'common:demo.react.forcedPreview'
  | 'common:demo.react.globalTitle'
  | 'common:demo.react.hookTitle'
  | 'common:demo.react.observedLanguage'
  | 'common:demo.react.title'
  | 'common:demo.sections.interpolation.body'
  | 'common:demo.sections.interpolation.title'
  | 'common:demo.sections.plural.body'
  | 'common:demo.sections.plural.title'
  | 'common:environment'
  | 'common:footer.copyright'
  | 'common:footer.madeWith'
  | 'common:greeting'
  | 'common:layout.titleSuffix'
  | 'common:nav.brand'
  | 'common:nav.changeLanguage'
  | 'common:nav.demo'
  | 'common:nav.features'
  | 'common:nav.frameworks'
  | 'common:nav.home'
  | 'common:notifications.count'
  | 'common:notifications.count_one'
  | 'common:notifications.count_other'
  | 'common:notifications.count_zero'
  | 'common:routing.body'
  | 'common:routing.currentPath'
  | 'common:routing.linkBrazil'
  | 'common:routing.linkEnglish'
  | 'common:routing.linkHome'
  | 'common:routing.title'
  | 'common:sections.server.body'
  | 'common:sections.server.title'
  | 'common:sections.variables.body'
  | 'common:sections.variables.title'
  | 'controls.body'
  | 'controls.clientStatus'
  | 'controls.title'
  | 'demo.meta.description'
  | 'demo.meta.pageTitle'
  | 'demo.react.currentLanguage'
  | 'demo.react.description'
  | 'demo.react.eventCount'
  | 'demo.react.forcedPreview'
  | 'demo.react.globalTitle'
  | 'demo.react.hookTitle'
  | 'demo.react.observedLanguage'
  | 'demo.react.title'
  | 'demo.sections.interpolation.body'
  | 'demo.sections.interpolation.title'
  | 'demo.sections.plural.body'
  | 'demo.sections.plural.title'
  | 'environment'
  | 'features:code.caption'
  | 'features:code.snippet'
  | 'features:compare.feature'
  | 'features:compare.native'
  | 'features:compare.plugin'
  | 'features:fallbackExample.hint'
  | 'features:fallbackExample.line'
  | 'features:fallbackExample.title'
  | 'features:headings.code'
  | 'features:headings.compare'
  | 'features:headings.list'
  | 'features:intro'
  | 'features:list.audit'
  | 'features:list.declarative'
  | 'features:list.namespaces'
  | 'features:list.plural'
  | 'features:list.seo'
  | 'features:meta.description'
  | 'features:meta.pageTitle'
  | 'features:rows.bundles.feature'
  | 'features:rows.bundles.native'
  | 'features:rows.bundles.plugin'
  | 'features:rows.routing.feature'
  | 'features:rows.routing.native'
  | 'features:rows.routing.plugin'
  | 'features:rows.ssr.feature'
  | 'features:rows.ssr.native'
  | 'features:rows.ssr.plugin'
  | 'features:title'
  | 'footer.copyright'
  | 'footer.madeWith'
  | 'frameworks:changeLanguage.react'
  | 'frameworks:changeLanguage.solid'
  | 'frameworks:changeLanguage.svelte'
  | 'frameworks:changeLanguage.vue'
  | 'frameworks:code.react'
  | 'frameworks:code.solid'
  | 'frameworks:code.svelte'
  | 'frameworks:code.vue'
  | 'frameworks:counter.items'
  | 'frameworks:counter.items_one'
  | 'frameworks:counter.items_other'
  | 'frameworks:counter.items_zero'
  | 'frameworks:frameworks.description'
  | 'frameworks:frameworks.title'
  | 'greeting'
  | 'home:cards.dx.body'
  | 'home:cards.dx.title'
  | 'home:cards.islands.body'
  | 'home:cards.islands.title'
  | 'home:cards.lazy.body'
  | 'home:cards.lazy.title'
  | 'home:cards.routing.body'
  | 'home:cards.routing.title'
  | 'home:hero.declarativeHint'
  | 'home:hero.subtitle'
  | 'home:hero.title'
  | 'home:meta.description'
  | 'home:meta.pageTitle'
  | 'home:tryIt.body'
  | 'home:tryIt.ctaDemo'
  | 'home:tryIt.ctaFeatures'
  | 'home:tryIt.title'
  | 'layout.titleSuffix'
  | 'nav.brand'
  | 'nav.changeLanguage'
  | 'nav.demo'
  | 'nav.features'
  | 'nav.frameworks'
  | 'nav.home'
  | 'notifications.count'
  | 'notifications.count_one'
  | 'notifications.count_other'
  | 'notifications.count_zero'
  | 'routing.body'
  | 'routing.currentPath'
  | 'routing.linkBrazil'
  | 'routing.linkEnglish'
  | 'routing.linkHome'
  | 'routing.title'
  | 'sections.server.body'
  | 'sections.server.title'
  | 'sections.variables.body'
  | 'sections.variables.title';

export type GeneratedTranslationKey = I18nKey;

/**
 * Options for translation functions like `t`.
 */
export interface I18nOptions {
  values?: Record<string, string | number | boolean>;
  lang?: Lang;
}

export type GeneratedTranslationOptions = I18nOptions;

/**
 * Helper type for the t function signature.
 */
export type TFunction = (key: I18nKey, options?: I18nOptions) => string;

/**
 * Object containing all available translation keys.
 */
export const I18N_KEYS = {
  'common:controls.body': 'common:controls.body',
  'common:controls.clientStatus': 'common:controls.clientStatus',
  'common:controls.title': 'common:controls.title',
  'common:demo.meta.description': 'common:demo.meta.description',
  'common:demo.meta.pageTitle': 'common:demo.meta.pageTitle',
  'common:demo.react.currentLanguage': 'common:demo.react.currentLanguage',
  'common:demo.react.description': 'common:demo.react.description',
  'common:demo.react.eventCount': 'common:demo.react.eventCount',
  'common:demo.react.forcedPreview': 'common:demo.react.forcedPreview',
  'common:demo.react.globalTitle': 'common:demo.react.globalTitle',
  'common:demo.react.hookTitle': 'common:demo.react.hookTitle',
  'common:demo.react.observedLanguage': 'common:demo.react.observedLanguage',
  'common:demo.react.title': 'common:demo.react.title',
  'common:demo.sections.interpolation.body': 'common:demo.sections.interpolation.body',
  'common:demo.sections.interpolation.title': 'common:demo.sections.interpolation.title',
  'common:demo.sections.plural.body': 'common:demo.sections.plural.body',
  'common:demo.sections.plural.title': 'common:demo.sections.plural.title',
  'common:environment': 'common:environment',
  'common:footer.copyright': 'common:footer.copyright',
  'common:footer.madeWith': 'common:footer.madeWith',
  'common:greeting': 'common:greeting',
  'common:layout.titleSuffix': 'common:layout.titleSuffix',
  'common:nav.brand': 'common:nav.brand',
  'common:nav.changeLanguage': 'common:nav.changeLanguage',
  'common:nav.demo': 'common:nav.demo',
  'common:nav.features': 'common:nav.features',
  'common:nav.frameworks': 'common:nav.frameworks',
  'common:nav.home': 'common:nav.home',
  'common:notifications.count': 'common:notifications.count',
  'common:notifications.count_one': 'common:notifications.count_one',
  'common:notifications.count_other': 'common:notifications.count_other',
  'common:notifications.count_zero': 'common:notifications.count_zero',
  'common:routing.body': 'common:routing.body',
  'common:routing.currentPath': 'common:routing.currentPath',
  'common:routing.linkBrazil': 'common:routing.linkBrazil',
  'common:routing.linkEnglish': 'common:routing.linkEnglish',
  'common:routing.linkHome': 'common:routing.linkHome',
  'common:routing.title': 'common:routing.title',
  'common:sections.server.body': 'common:sections.server.body',
  'common:sections.server.title': 'common:sections.server.title',
  'common:sections.variables.body': 'common:sections.variables.body',
  'common:sections.variables.title': 'common:sections.variables.title',
  'controls.body': 'controls.body',
  'controls.clientStatus': 'controls.clientStatus',
  'controls.title': 'controls.title',
  'demo.meta.description': 'demo.meta.description',
  'demo.meta.pageTitle': 'demo.meta.pageTitle',
  'demo.react.currentLanguage': 'demo.react.currentLanguage',
  'demo.react.description': 'demo.react.description',
  'demo.react.eventCount': 'demo.react.eventCount',
  'demo.react.forcedPreview': 'demo.react.forcedPreview',
  'demo.react.globalTitle': 'demo.react.globalTitle',
  'demo.react.hookTitle': 'demo.react.hookTitle',
  'demo.react.observedLanguage': 'demo.react.observedLanguage',
  'demo.react.title': 'demo.react.title',
  'demo.sections.interpolation.body': 'demo.sections.interpolation.body',
  'demo.sections.interpolation.title': 'demo.sections.interpolation.title',
  'demo.sections.plural.body': 'demo.sections.plural.body',
  'demo.sections.plural.title': 'demo.sections.plural.title',
  'environment': 'environment',
  'features:code.caption': 'features:code.caption',
  'features:code.snippet': 'features:code.snippet',
  'features:compare.feature': 'features:compare.feature',
  'features:compare.native': 'features:compare.native',
  'features:compare.plugin': 'features:compare.plugin',
  'features:fallbackExample.hint': 'features:fallbackExample.hint',
  'features:fallbackExample.line': 'features:fallbackExample.line',
  'features:fallbackExample.title': 'features:fallbackExample.title',
  'features:headings.code': 'features:headings.code',
  'features:headings.compare': 'features:headings.compare',
  'features:headings.list': 'features:headings.list',
  'features:intro': 'features:intro',
  'features:list.audit': 'features:list.audit',
  'features:list.declarative': 'features:list.declarative',
  'features:list.namespaces': 'features:list.namespaces',
  'features:list.plural': 'features:list.plural',
  'features:list.seo': 'features:list.seo',
  'features:meta.description': 'features:meta.description',
  'features:meta.pageTitle': 'features:meta.pageTitle',
  'features:rows.bundles.feature': 'features:rows.bundles.feature',
  'features:rows.bundles.native': 'features:rows.bundles.native',
  'features:rows.bundles.plugin': 'features:rows.bundles.plugin',
  'features:rows.routing.feature': 'features:rows.routing.feature',
  'features:rows.routing.native': 'features:rows.routing.native',
  'features:rows.routing.plugin': 'features:rows.routing.plugin',
  'features:rows.ssr.feature': 'features:rows.ssr.feature',
  'features:rows.ssr.native': 'features:rows.ssr.native',
  'features:rows.ssr.plugin': 'features:rows.ssr.plugin',
  'features:title': 'features:title',
  'footer.copyright': 'footer.copyright',
  'footer.madeWith': 'footer.madeWith',
  'frameworks:changeLanguage.react': 'frameworks:changeLanguage.react',
  'frameworks:changeLanguage.solid': 'frameworks:changeLanguage.solid',
  'frameworks:changeLanguage.svelte': 'frameworks:changeLanguage.svelte',
  'frameworks:changeLanguage.vue': 'frameworks:changeLanguage.vue',
  'frameworks:code.react': 'frameworks:code.react',
  'frameworks:code.solid': 'frameworks:code.solid',
  'frameworks:code.svelte': 'frameworks:code.svelte',
  'frameworks:code.vue': 'frameworks:code.vue',
  'frameworks:counter.items': 'frameworks:counter.items',
  'frameworks:counter.items_one': 'frameworks:counter.items_one',
  'frameworks:counter.items_other': 'frameworks:counter.items_other',
  'frameworks:counter.items_zero': 'frameworks:counter.items_zero',
  'frameworks:frameworks.description': 'frameworks:frameworks.description',
  'frameworks:frameworks.title': 'frameworks:frameworks.title',
  'greeting': 'greeting',
  'home:cards.dx.body': 'home:cards.dx.body',
  'home:cards.dx.title': 'home:cards.dx.title',
  'home:cards.islands.body': 'home:cards.islands.body',
  'home:cards.islands.title': 'home:cards.islands.title',
  'home:cards.lazy.body': 'home:cards.lazy.body',
  'home:cards.lazy.title': 'home:cards.lazy.title',
  'home:cards.routing.body': 'home:cards.routing.body',
  'home:cards.routing.title': 'home:cards.routing.title',
  'home:hero.declarativeHint': 'home:hero.declarativeHint',
  'home:hero.subtitle': 'home:hero.subtitle',
  'home:hero.title': 'home:hero.title',
  'home:meta.description': 'home:meta.description',
  'home:meta.pageTitle': 'home:meta.pageTitle',
  'home:tryIt.body': 'home:tryIt.body',
  'home:tryIt.ctaDemo': 'home:tryIt.ctaDemo',
  'home:tryIt.ctaFeatures': 'home:tryIt.ctaFeatures',
  'home:tryIt.title': 'home:tryIt.title',
  'layout.titleSuffix': 'layout.titleSuffix',
  'nav.brand': 'nav.brand',
  'nav.changeLanguage': 'nav.changeLanguage',
  'nav.demo': 'nav.demo',
  'nav.features': 'nav.features',
  'nav.frameworks': 'nav.frameworks',
  'nav.home': 'nav.home',
  'notifications.count': 'notifications.count',
  'notifications.count_one': 'notifications.count_one',
  'notifications.count_other': 'notifications.count_other',
  'notifications.count_zero': 'notifications.count_zero',
  'routing.body': 'routing.body',
  'routing.currentPath': 'routing.currentPath',
  'routing.linkBrazil': 'routing.linkBrazil',
  'routing.linkEnglish': 'routing.linkEnglish',
  'routing.linkHome': 'routing.linkHome',
  'routing.title': 'routing.title',
  'sections.server.body': 'sections.server.body',
  'sections.server.title': 'sections.server.title',
  'sections.variables.body': 'sections.variables.body',
  'sections.variables.title': 'sections.variables.title'
} as const;

/**
 * Module augmentation: conecta los tipos generados con la API pública del plugin.
 */
declare module "@gschz/astro-plugin-i18n" {
  interface AstroI18nTypeRegistry {
    Language: Lang;
    TranslationKey: I18nKey;
  }
}

declare module "@gschz/astro-plugin-i18n/client" {
  interface AstroI18nTypeRegistry {
    Language: Lang;
    TranslationKey: I18nKey;
  }
}

export {};
