/**
 * Generador de tipos TypeScript para claves de traducción.
 *
 * Esta utilidad la invoca la integración cuando `generateTypes` está habilitado.
 * Genera un `.d.ts` que hace module augmentation sobre la API pública del plugin,
 * de modo que `Language` y `TranslationKey` se tipen con datos reales del
 * proyecto consumidor en lugar de quedarse como `string` genérico.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { TranslationConfig } from '../types';
import { getConfig, getDefaultLanguage } from '../core/config';
import { loadTranslations } from '../core/translations';

/**
 * Genera un archivo `.d.ts` con tipos derivados del idioma por defecto.
 *
 * @returns Ruta absoluta del archivo generado, o cadena vacía si no hubo claves.
 */
export async function generateTranslationTypes(): Promise<string> {
  const config = getConfig();
  const defaultLang = getDefaultLanguage();
  const translations = await loadTranslations(defaultLang);

  if (!translations || Object.keys(translations).length === 0) {
    console.warn(
      `[i18n-types] No translations found for default language '${defaultLang}' at '${config.translationsDir}'. Types will not be generated.`,
    );
    return '';
  }

  const typeDefinitionCode = generateTypeDefinitionCode(translations, config.supportedLangs || [], config);

  const outputPath = path.resolve(process.cwd(), config.typesOutputPath || './src/types/i18n-types.d.ts');
  const dirPath = path.dirname(outputPath);

  try {
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }

    fs.writeFileSync(outputPath, typeDefinitionCode, 'utf-8');
    return outputPath;
  } catch (error) {
    console.error(`[i18n-types] Failed to write types file to ${outputPath}:`, error);

    throw new Error(`Failed to write i18n types file: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/**
 * Construye el contenido TypeScript del archivo generado.
 *
 * Mantiene aliases legacy (`Lang`, `I18nKey`) por compatibilidad, pero además
 * exporta nombres más explícitos para nuevos consumidores.
 */
function generateTypeDefinitionCode(
  translations: Record<string, any>,
  supportedLangs: string[],
  config: TranslationConfig,
): string {
  let code = `// This file is automatically generated by @gschz/astro-plugin-i18n
// Do not modify it manually, as it will be overwritten.

/**
 * Types for the i18n system generated from the default language translations.
 */

`;

  code += `/**
 * Type representing the supported language codes.
 */
`;

  const langType =
    supportedLangs.length > 0 ? supportedLangs.map((lang) => `'${escapeTsStringLiteral(lang)}'`).join(' | ') : 'string';

  code += `export type Lang = ${langType};
export type GeneratedLanguage = Lang;

`;

  code += `/**
 * Type representing all available translation keys.
 */
`;

  const keys = collectTranslationKeys(translations, config);
  keys.sort((a, b) => a.localeCompare(b));

  if (keys.length === 0) {
    code += `export type I18nKey = string; // No keys found in default language file
`;
  } else {
    code += `export type I18nKey =
`;
    code += keys.map((key) => `  | '${escapeTsStringLiteral(key)}'`).join('\n');
    code += `;
`;
  }

  code += `
export type GeneratedTranslationKey = I18nKey;

/**
 * Options for translation functions like \`t\`.
 */
export interface I18nOptions {
  values?: Record<string, string | number | boolean>;
  lang?: Lang;
}

export type GeneratedTranslationOptions = I18nOptions;

/**
 * Helper type for the t function signature.
 */
export type TFunction = (key: I18nKey, options?: I18nOptions) => string;

/**
 * Object containing all available translation keys.
 */
export const I18N_KEYS = {
`;

  code += keys.map((key) => `  '${escapeTsStringLiteral(key)}': '${escapeTsStringLiteral(key)}',`).join('\n');

  if (code.endsWith(',')) {
    code = code.slice(0, -1);
  }

  code += `
} as const;

/**
 * Module augmentation: conecta los tipos generados con la API pública del plugin.
 */
declare module "@gschz/astro-plugin-i18n" {
  interface AstroI18nTypeRegistry {
    Language: Lang;
    TranslationKey: I18nKey;
  }
}

declare module "@gschz/astro-plugin-i18n/client" {
  interface AstroI18nTypeRegistry {
    Language: Lang;
    TranslationKey: I18nKey;
  }
}

export {};
`;

  return code;
}

function escapeTsStringLiteral(value: string): string {
  const json = JSON.stringify(value);
  const inner = json.slice(1, -1);
  return inner.replaceAll("'", String.raw`\'`);
}

/**
 * Recolecta claves de traduccion considerando namespaces y pluralizacion.
 *
 * @param translations - Bundle del idioma por defecto.
 * @param config - Configuracion i18n normalizada.
 * @returns Lista de claves a exportar.
 */
function collectTranslationKeys(translations: Record<string, any>, config: TranslationConfig): string[] {
  const keys = new Set<string>();
  const useNamespaces = config.namespaces?.enabled === true;
  const pluralizationEnabled = config.pluralization?.enabled !== false;

  if (useNamespaces && isNamespacedBundle(translations)) {
    collectNamespacedKeys(translations, config, keys, pluralizationEnabled);
  } else {
    const legacyKeys: string[] = [];
    extractKeysRecursive(translations, '', legacyKeys);
    for (const key of legacyKeys) {
      addKeyWithPluralSupport(keys, key, pluralizationEnabled);
    }
  }

  return Array.from(keys);
}

/**
 * Recolecta claves para un bundle con namespaces.
 *
 * @param translations - Bundle con namespaces.
 * @param config - Configuracion i18n.
 * @param keys - Set de claves acumuladas.
 * @param pluralizationEnabled - Si pluralizacion esta activa.
 */
function collectNamespacedKeys(
  translations: Record<string, any>,
  config: TranslationConfig,
  keys: Set<string>,
  pluralizationEnabled: boolean,
): void {
  const namespaceConfig = config.namespaces;
  const separator = namespaceConfig?.separator ?? ':';
  const defaultNamespace = namespaceConfig?.defaultNamespace ?? 'common';

  for (const [namespace, namespaceTranslations] of Object.entries(translations)) {
    if (typeof namespaceTranslations !== 'object' || namespaceTranslations === null) {
      continue;
    }

    const namespaceKeys: string[] = [];
    extractKeysRecursive(namespaceTranslations as Record<string, any>, '', namespaceKeys);

    for (const key of namespaceKeys) {
      addKeyWithPluralSupport(keys, `${namespace}${separator}${key}`, pluralizationEnabled);

      if (namespace === defaultNamespace) {
        addKeyWithPluralSupport(keys, key, pluralizationEnabled);
      }
    }
  }
}

/**
 * Detecta si el bundle tiene namespaces en el primer nivel.
 *
 * @param translations - Bundle de traducciones.
 * @returns `true` si parece namespaced.
 */
function isNamespacedBundle(translations: Record<string, any>): boolean {
  const values = Object.values(translations || {});
  return values.length > 0 && values.every((value) => typeof value === 'object' && value !== null);
}

/**
 * Agrega una clave y, si aplica, su version sin sufijo plural.
 *
 * @param keys - Set de claves acumuladas.
 * @param key - Clave candidata.
 * @param pluralizationEnabled - Si pluralizacion esta activa.
 */
function addKeyWithPluralSupport(keys: Set<string>, key: string, pluralizationEnabled: boolean): void {
  keys.add(key);

  if (!pluralizationEnabled) {
    return;
  }

  const baseKey = stripPluralSuffix(key);
  if (baseKey !== key) {
    keys.add(baseKey);
  }
}

/**
 * Elimina el sufijo plural de una clave.
 *
 * @param key - Clave con posible sufijo plural.
 * @returns Clave base.
 */
function stripPluralSuffix(key: string): string {
  return key.replace(/_(zero|one|two|few|many|other)$/, '');
}

/**
 * Recorre recursivamente el JSON y extrae todas las claves hoja en notacion de puntos.
 *
 * @param obj - Objeto de traducciones.
 * @param prefix - Prefijo acumulado.
 * @param keys - Array de salida.
 */
function extractKeysRecursive(obj: Record<string, any>, prefix: string, keys: string[]): void {
  for (const key in obj) {
    const fullKey = prefix ? `${prefix}.${key}` : key;

    if (typeof obj[key] === 'object' && obj[key] !== null) {
      extractKeysRecursive(obj[key], fullKey, keys);
    } else {
      keys.push(fullKey);
    }
  }
}
