/**
 * Generador de tipos TypeScript para claves de traducción.
 *
 * Esta utilidad la invoca la integración cuando `generateTypes` está habilitado.
 * Genera un `.d.ts` que hace module augmentation sobre la API pública del plugin,
 * de modo que `Language` y `TranslationKey` se tipen con datos reales del
 * proyecto consumidor en lugar de quedarse como `string` genérico.
 */

import fs from 'node:fs';
import path from 'node:path';
import { getConfig, getDefaultLanguage } from '../core/config';
import { loadTranslations } from '../core/translations';

/**
 * Genera un archivo `.d.ts` con tipos derivados del idioma por defecto.
 *
 * @returns Ruta absoluta del archivo generado, o cadena vacía si no hubo claves.
 */
export async function generateTranslationTypes(): Promise<string> {
  const config = getConfig();
  const defaultLang = getDefaultLanguage();
  const translations = await loadTranslations(defaultLang);

  if (!translations || Object.keys(translations).length === 0) {
    console.warn(
      `[i18n-types] No translations found for default language '${defaultLang}' at '${config.translationsDir}'. Types will not be generated.`,
    );
    return '';
  }

  const typeDefinitionCode = generateTypeDefinitionCode(translations, config.supportedLangs || []);

  const outputPath = path.resolve(process.cwd(), config.typesOutputPath || './src/types/i18n-types.d.ts');
  const dirPath = path.dirname(outputPath);

  try {
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }

    fs.writeFileSync(outputPath, typeDefinitionCode, 'utf-8');
    console.info(`[i18n-types] Successfully generated translation types at: ${outputPath}`);
    return outputPath;
  } catch (error) {
    console.error(`[i18n-types] Failed to write types file to ${outputPath}:`, error);

    throw new Error(`Failed to write i18n types file: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/**
 * Construye el contenido TypeScript del archivo generado.
 *
 * Mantiene aliases legacy (`Lang`, `I18nKey`) por compatibilidad, pero además
 * exporta nombres más explícitos para nuevos consumidores.
 */
function generateTypeDefinitionCode(translations: Record<string, any>, supportedLangs: string[]): string {
  let code = `// This file is automatically generated by @gschz/astro-plugin-i18n
// Do not modify it manually, as it will be overwritten.

/**
 * Types for the i18n system generated from the default language translations.
 */

`;

  code += `/**
 * Type representing the supported language codes.
 */
`;

  const langType =
    supportedLangs.length > 0 ? supportedLangs.map((lang) => `'${escapeTsStringLiteral(lang)}'`).join(' | ') : 'string';

  code += `export type Lang = ${langType};
export type GeneratedLanguage = Lang;

`;

  code += `/**
 * Type representing all available translation keys.
 */
`;

  const keys: string[] = [];
  extractKeysRecursive(translations, '', keys);
  keys.sort();

  if (keys.length === 0) {
    code += `export type I18nKey = string; // No keys found in default language file
`;
  } else {
    code += `export type I18nKey =
`;
    code += keys.map((key) => `  | '${escapeTsStringLiteral(key)}'`).join('\n');
    code += `;
`;
  }

  code += `
export type GeneratedTranslationKey = I18nKey;

/**
 * Options for translation functions like \`t\`.
 */
export interface I18nOptions {
  values?: Record<string, string | number | boolean>;
  lang?: Lang;
}

export type GeneratedTranslationOptions = I18nOptions;

/**
 * Helper type for the t function signature.
 */
export type TFunction = (key: I18nKey, options?: I18nOptions) => string;

/**
 * Object containing all available translation keys.
 */
export const I18N_KEYS = {
`;

  code += keys.map((key) => `  '${escapeTsStringLiteral(key)}': '${escapeTsStringLiteral(key)}',`).join('\n');

  if (code.endsWith(',')) {
    code = code.slice(0, -1);
  }

  code += `
} as const;

/**
 * Module augmentation: conecta los tipos generados con la API pública del plugin.
 */
declare module "@gschz/astro-plugin-i18n" {
  interface AstroI18nTypeRegistry {
    Language: Lang;
    TranslationKey: I18nKey;
  }
}

declare module "@gschz/astro-plugin-i18n/client" {
  interface AstroI18nTypeRegistry {
    Language: Lang;
    TranslationKey: I18nKey;
  }
}

export {};
`;

  return code;
}

function escapeTsStringLiteral(value: string): string {
  const json = JSON.stringify(value);
  const inner = json.slice(1, -1);
  return inner.replace(/'/g, "\\'");
}

/** Recorre recursivamente el JSON y extrae todas las claves hoja en notación de puntos. */
function extractKeysRecursive(obj: Record<string, any>, prefix: string, keys: string[]): void {
  for (const key in obj) {
    const fullKey = prefix ? `${prefix}.${key}` : key;

    if (typeof obj[key] === 'object' && obj[key] !== null) {
      extractKeysRecursive(obj[key], fullKey, keys);
    } else {
      keys.push(fullKey);
    }
  }
}
